### ISSUE TITLE
Yaegi plugin framework

### ISSUE THREAD

**Issue by kevinduffey** [uberswe/go-plugin-benchmark#2]
Wondering if Yaegi was looked at and considered for benchmarking? Seems like a pretty slick way to support plugins with minimal performance hit based on tests by the Traefik team.

**Comment by uberswe** [comment]
I think it could be interesting to compare. [Yaegi](https://github.com/traefik/yaegi) is an interpreter which makes it different from the other plugin solutions but it will still be viable or even better for many use cases. I will see if I can add it this weekend.

**Comment by uberswe** [comment]
@kevinduffey thank you for your question. I have added a benchmark for Yaegi now.

**Comment by kevinduffey** [comment]
Excellent! Thank you for such a quick addition. From the benchmark, it looks like it stacks up better than all but the go native plugin code.. am I reading that right? How did you feel about the implementation vs others? I am playing around with it still and finding it interesting but a bit limited.. namely I want a plugin to be able to provide an interface that another plugin can implement.. doesn't seem likely that that will work.

**Comment by uberswe** [comment]
Yes, it performed better than I thought it would and it was interesting to give it a go. So, as you say, it does indeed perform better than all the other plugin solutions except the go native plugin code. I think interpreted code may have a different use case from RPC/gRPC plugins but it's nice to include it here in the benchmark.

As for an interface, you could provide a package with interfaces which can be implemented in code which will then be called by the interpreter. On this example from the documentation you can see how a function could be implemented:  https://github.com/traefik/yaegi#as-a-dynamic-extension-framework. This function could take input from the main application or another plugin and do something with it.

I guess there is also different security implications of the go plugin approach versus interpreted code. With most plugin solutions you basically have a separate application instance running which can do anything it wants in its environment. Here you interpret code and you could modify and limit what it is capable of doing which may make it safer. 

As for this benchmark, we are only checking a simple function which returns a random integer. I think it would be interesting to compare performance for more complex operations and also the time it takes to load the plugin or code in the first place before calling the function. The benchmark can be useful and I find it interesting but it doesn't give you the full picture.
