### ISSUE TITLE
goloader benchmark 

### ISSUE THREAD

**Issue by fumin** [uberswe/go-plugin-benchmark#4]
Could you add a comparison for

https://github.com/pkujhd/goloader

Thanks

**Comment by uberswe** [comment]
Looks interesting. I will try it out to see if I can get it working well with the rest of the tests. Hopefully I will have some time this weekend but if anyone else wants to give it a go feel free to open a PR.

**Comment by uberswe** [comment]
@fumin thanks, I have now added the benchmark

**Comment by fumin** [comment]
Great work @uberswe , thanks!
Your conclusions in the README is very informative, and really paints a complete picture of the plugin landscape of Go.
